#!/usr/bin/env bash
# Configure my domain zone:
# www --> 39209-lb-01 18.214.89.19
# lb-01 --> 39209-lb-01 18.214.89.19
# web-01 --> 39209-web-01 54.174.165.251
# web-02 --> 39209-web-02 100.24.236.227

dns_info_analyzer() {
	result=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION'| tail -1 | awk '{print $4 " " $5}')
	echo "$result" "$2" | awk '{print "The subdomain " $3 " is a " $1 " record and points to " $2}'
}

if [ "$#" == 2 ]
then
	dns_info_analyzer "$1" "$2"
else
	dns_info_analyzer "$1" "www"
	dns_info_analyzer "$1" "lb-01"
	dns_info_analyzer "$1" "web-01"
	dns_info_analyzer "$1" "web-02"
fi
