#!/usr/bin/env bash
# prints To infinity and beyond indefinitly

sleep_counter=2

while true
do
    for (( i=0; i <= $sleep_counter; i++ ))
    do
        echo "To infinity and beyond"
        sleep 2
    done
done
