#!/usr/bin/env bash

#Bash script that displays numbers from 1 to 100.
#FizzBuzz when the number is a multiple of 3 and 5
#Fizz when number is multiple if 3
#Buzz when number is multiple if 5

for n in {1..100}
do
    if (( n % 3 == 0 && n % 5 == 0 ))
    then
        echo "FizzBuzz"
    elif (( n % 3 == 0 ))
    then
        echo "Fizz"
    elif (( n % 5 == 0 ))
    then
        echo "Buzz"
    else
        echo "$n"
    fi
done
