#!/usr/bin/env bash
#Write a Bash script that displays the time for 12 hours and 59 minutes:
#
#    display hours from 0 to 12
#    display minutes from 1 to 59
#
#Requirements:
#
#    You must use the while loop (for and until are forbidden)
#
#Note that in this example, we only display the first 70 lines using the head command.

i=0

echo "Hour: $i"
i=1
while [ $i -lt 60 ]

do
    echo $i
    ((i++))
    if [ $i -eq 60 ]
    then
        echo "Hour: 1"
        j=1
        while [ $j -lt 10 ]
        do
            echo $j
            ((j++))
        done
    fi
done
